seml:
  name: train_inductive_sparse
  executable: experiment_train_inductive.py
  project_root_dir: ../..
  output_dir: config/train/output

slurm:
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:1       # num GPUs
    mem: 16G
    cpus-per-task: 4  # num cores
    time: 0-01:00     # max time, D-HH:MM

fixed:
  train_params:
    lr: 1e-2
    weight_decay: 1e-3
    patience: 300
    max_epochs: 3000
  artifact_dir: cache
  model_storage_type: overrobust
  device: 0
  data_device: 0
  data_dir: datasets/
  make_undirected: True
  binary_attr: False
  n_per_class: [20, 20, 40] # if list here, dense_split must be false
  dense_split: False

grid:
  seed:
    type: choice
    options:
      - 0
      - 1
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
  dataset: 
    type: choice
    options:
      - cora_ml
      - Cora
      - citeseer
      - pubmed

gcn:
  fixed:
    model_params:
      label: GCN
      model: GCN
      do_cache_adj_prep: False
      n_filters: 64
      dropout: 0.5
      svd_params: None
      jaccard_params: None
      gdc_params: None

# appnp:
#   fixed: 
#     model_params:
#       label: APPNP
#       model: APPNP
#       K: 10
#       alpha: 0.1
#       dropout: 0.5
#       add_self_loops: True
#       cached: False
#       n_hidden: 64