seml:
  name: r_sgc_lp
  executable: exp_eval_robustness.py
  project_root_dir: ../../../
  output_dir: log/eval_robustness/

slurm:
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:1       # num GPUs
    mem: 10G          # memory
    cpus-per-task: 4  # num cores
    time: 0-08:30     # max time, D-HH:MM

fixed:
  model_params:
    label: SGC+LP
    model: SGC
    use_label_propagation: True
    lp_layers: 50
    lp_alpha: 0.7
    lp_use_clamping: False

  data_params:
    inductive_samples: 1000
  
  train_params:
    inductive: True

  other_params:
    device: cpu
    sacred_metrics: False

grid:
  attack_params:
    max_robustness:
      type: choice
      options:
        - 999
    attack: 
      type: choice
      options:
      - "l2"
      - "random"
      - "l2-weak"
      - SGA
      - "nettack"
  
  seed:
    type: range
    min: 0
    max: 10
    step: 1

K01:
  fixed:
    data_params:
      K: 0.1

    model_params:
      dropout: 0.3
      K: 5

    train_params:
      lr: 0.2
      weight_decay: 0.0001

    attack_params:
      surrogate_model_params:
        label: "LinearGCN"
        model: "LinearGCN"
        n_filter: 64
        dropout: 0.5
      surrogate_train_params:
        lr: 0.1
        weight_decay: 0.0001
        patience: 300
        max_epochs: 3000

K05:
  fixed:
    data_params:
      K: 0.5

    model_params:
      dropout: 0.0
      K: 5

    train_params:
      lr: 0.2
      weight_decay: 0.0001

    attack_params:
      surrogate_model_params:
        label: "LinearGCN"
        model: "LinearGCN"
        n_filter: 64
        dropout: 0.5
      surrogate_train_params:
        lr: 0.1
        weight_decay: 0.0001
        patience: 300
        max_epochs: 3000

K1:
  fixed:
    data_params:
      K: 1.0

    model_params:
      dropout: 0.0
      K: 4

    train_params:
      lr: 0.2
      weight_decay: 0.0001

    attack_params:
      surrogate_model_params:
        label: "LinearGCN"
        model: "LinearGCN"
        n_filter: 64
        dropout: 0.5
      surrogate_train_params:
        lr: 0.1
        weight_decay: 0.0001
        patience: 300
        max_epochs: 3000

K15:
  fixed:
    data_params:
      K: 1.5

    model_params:
      dropout: 0.0
      K: 2

    train_params:
      lr: 0.2
      weight_decay: 0.0010

    attack_params:
      surrogate_model_params:
        label: "LinearGCN"
        model: "LinearGCN"
        n_filter: 64
        dropout: 0.5
      surrogate_train_params:
        lr: 0.1
        weight_decay: 0.0001
        patience: 300
        max_epochs: 3000

K2:
  fixed:
    data_params:
      K: 2.0

    model_params:
      dropout: 0.3
      K: 2

    train_params:
      lr: 0.2
      weight_decay: 0.0001

    attack_params:
      surrogate_model_params:
        label: "LinearGCN"
        model: "LinearGCN"
        n_filter: 64
        dropout: 0.5
      surrogate_train_params:
        lr: 0.1
        weight_decay: 0.0001
        patience: 300
        max_epochs: 3000
K3:
  fixed:
    data_params:
      K: 3.0

    model_params:
      dropout: 0.3
      K: 2

    train_params:
      lr: 0.2
      weight_decay: 0.0001

    attack_params:
      surrogate_model_params:
        label: "LinearGCN"
        model: "LinearGCN"
        n_filter: 64
        dropout: 0.5
      surrogate_train_params:
        lr: 0.1
        weight_decay: 0.0010
        patience: 300
        max_epochs: 3000

K4:
  fixed:
    data_params:
      K: 4.0

    model_params:
      dropout: 0.5
      K: 1

    train_params:
      lr: 0.02
      weight_decay: 0.0001

    attack_params:
      surrogate_model_params:
        label: "LinearGCN"
        model: "LinearGCN"
        n_filter: 64
        dropout: 0.5
      surrogate_train_params:
        lr: 0.1
        weight_decay: 0.0100
        patience: 300
        max_epochs: 3000
        
K5:
  fixed:
    data_params:
      K: 5.0

    model_params:
      dropout: 0.5
      K: 1

    train_params:
      lr: 0.02
      weight_decay: 0.0001

    attack_params:
      surrogate_model_params:
        label: "LinearGCN"
        model: "LinearGCN"
        n_filter: 64
        dropout: 0.5
      surrogate_train_params:
        lr: 0.1
        weight_decay: 0.0100
        patience: 300
        max_epochs: 3000