seml:
  name: r_gat_lp
  executable: exp_eval_robustness.py
  project_root_dir: ../../../
  output_dir: log/eval_robustness

slurm:
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:1       # num gpu
    mem: 10G          # memory
    cpus-per-task: 1  # num cores
    time: 0-08:30     # max time, D-HH:MM

fixed:

  model_params:
    label: GAT+LP
    model: GAT
    n_heads: 8
    n_features_per_head: 8
    use_label_propagation: True
    lp_layers: 50
    lp_alpha: 0.7
    lp_use_clamping: False

  data_params:
    inductive_samples: 1000
  
  train_params:
    inductive: True

  other_params:
    sacred_metrics: False

grid:
  attack_params:
    max_robustness:
      type: choice
      options:
        - 100
    attack: 
      type: choice
      options:
      - GRBCD
  
  seed:
    type: choice
    options:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9

K01:
  fixed:
    data_params:
      K: 0.1

    model_params:
      dropout: 0.0
      dropout_neighbourhood: 0.6

    train_params:
      lr: 0.10
      weight_decay: 0.0001

    attack_params:
      surrogate_model_params:
        label: "LinearGCN"
        model: "LinearGCN"
        n_filter: 64
        dropout: 0.5
      surrogate_train_params:
        lr: 0.1
        weight_decay: 0.0001
        patience: 300
        max_epochs: 3000

K05:
  fixed:
    data_params:
      K: 0.5

    model_params:
      dropout: 0.0
      dropout_neighbourhood: 0.3

    train_params:
      lr: 0.010
      weight_decay: 0.0001

    attack_params:
      surrogate_model_params:
        label: "LinearGCN"
        model: "LinearGCN"
        n_filter: 64
        dropout: 0.5
      surrogate_train_params:
        lr: 0.1
        weight_decay: 0.0001
        patience: 300
        max_epochs: 3000

K1:
  fixed:
    data_params:
      K: 1.0

    model_params:
      dropout: 0.0
      dropout_neighbourhood: 0.3

    train_params:
      lr: 0.10
      weight_decay: 0.0010

    attack_params:
      surrogate_model_params:
        label: "LinearGCN"
        model: "LinearGCN"
        n_filter: 64
        dropout: 0.5
      surrogate_train_params:
        lr: 0.1
        weight_decay: 0.0001
        patience: 300
        max_epochs: 3000

K15:
  fixed:
    data_params:
      K: 1.5

    model_params:
      dropout: 0.0
      dropout_neighbourhood: 0.6

    train_params:
      lr: 0.10
      weight_decay: 0.0001

    attack_params:
      surrogate_model_params:
        label: "LinearGCN"
        model: "LinearGCN"
        n_filter: 64
        dropout: 0.5
      surrogate_train_params:
        lr: 0.1
        weight_decay: 0.0001
        patience: 300
        max_epochs: 3000

K2:
  fixed:
    data_params:
      K: 2.0

    model_params:
      dropout: 0.0
      dropout_neighbourhood: 0.6

    train_params:
      lr: 0.10
      weight_decay: 0.0010

    attack_params:
      surrogate_model_params:
        label: "LinearGCN"
        model: "LinearGCN"
        n_filter: 64
        dropout: 0.5
      surrogate_train_params:
        lr: 0.1
        weight_decay: 0.0001
        patience: 300
        max_epochs: 3000

K3:
  fixed:
    data_params:
      K: 3.0

    model_params:
      dropout: 0.0
      dropout_neighbourhood: 0.3

    train_params:
      lr: 0.10
      weight_decay: 0.0010

    attack_params:
      surrogate_model_params:
        label: "LinearGCN"
        model: "LinearGCN"
        n_filter: 64
        dropout: 0.5
      surrogate_train_params:
        lr: 0.1
        weight_decay: 0.0001
        patience: 300
        max_epochs: 3000

K4:
  fixed:
    data_params:
      K: 4.0

    model_params:
      dropout: 0.0
      dropout_neighbourhood: 0.6

    train_params:
      lr: 0.10
      weight_decay: 0.0010

    attack_params:
      surrogate_model_params:
        label: "LinearGCN"
        model: "LinearGCN"
        n_filter: 64
        dropout: 0.5
      surrogate_train_params:
        lr: 0.1
        weight_decay: 0.0001
        patience: 300
        max_epochs: 3000

K5:
  fixed:
    data_params:
      K: 5.0

    model_params:
      dropout: 0.0
      dropout_neighbourhood: 0.0

    train_params:
      lr: 0.10
      weight_decay: 0.0010

    attack_params:
      surrogate_model_params:
        label: "LinearGCN"
        model: "LinearGCN"
        n_filter: 64
        dropout: 0.5
      surrogate_train_params:
        lr: 0.1
        weight_decay: 0.0100
        patience: 300
        max_epochs: 3000