seml:
  name: eval_robustness_lineargcn
  executable: exp_eval_robustness.py
  project_root_dir: ../../
  output_dir: log/eval_robustness/

slurm:
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:1       # num GPUs
    mem: 10G          # memory
    cpus-per-task: 4  # num cores
    time: 0-08:30     # max time, D-HH:MM

fixed:
  model_params:
    label: LinearGCN
    model: LinearGCN
    n_filters: 64

  data_params:
    inductive_samples: 1000
  
  train_params:
    inductive: True

  other_params:
    sacred_metrics: False

grid:
  attack_params:
    attack: 
      type: choice
      options:
      #- "l2"
      #- "random"
      #- "l2-weak"
      - "nettack"
  
  seed:
    type: range
    min: 0
    max: 10
    step: 1

K01:
  fixed:
    data_params:
      K: 0.1

    model_params:
      dropout: 0.5

    train_params:
      lr: 0.1
      weight_decay: 0.0001

    attack_params:
      surrogate_model_params:
        label: "LinearGCN"
        model: "LinearGCN"
        n_filter: 64
        dropout: 0.5
      surrogate_train_params:
        lr: 0.1
        weight_decay: 0.0001
        patience: 300
        max_epochs: 3000

K05:
  fixed:
    data_params:
      K: 0.5

    model_params:
      dropout: 0.5

    train_params:
      lr: 0.1
      weight_decay: 0.0001

    attack_params:
      surrogate_model_params:
        label: "LinearGCN"
        model: "LinearGCN"
        n_filter: 64
        dropout: 0.5
      surrogate_train_params:
        lr: 0.1
        weight_decay: 0.0001
        patience: 300
        max_epochs: 3000

K1:
  fixed:
    data_params:
      K: 1.0

    model_params:
      dropout: 0.5

    train_params:
      lr: 0.1
      weight_decay: 0.0001

    attack_params:
      surrogate_model_params:
        label: "LinearGCN"
        model: "LinearGCN"
        n_filter: 64
        dropout: 0.5
      surrogate_train_params:
        lr: 0.1
        weight_decay: 0.0001
        patience: 300
        max_epochs: 3000

K15:
  fixed:
    data_params:
      K: 1.5

    model_params:
      dropout: 0.5

    train_params:
      lr: 0.1
      weight_decay: 0.0001

    attack_params:
      surrogate_model_params:
        label: "LinearGCN"
        model: "LinearGCN"
        n_filter: 64
        dropout: 0.5
      surrogate_train_params:
        lr: 0.1
        weight_decay: 0.0001
        patience: 300
        max_epochs: 3000

K2:
  fixed:
    data_params:
      K: 2.0

    model_params:
      dropout: 0.5

    train_params:
      lr: 0.1
      weight_decay: 0.0001

    attack_params:
      surrogate_model_params:
        label: "LinearGCN"
        model: "LinearGCN"
        n_filter: 64
        dropout: 0.5
      surrogate_train_params:
        lr: 0.1
        weight_decay: 0.0001
        patience: 300
        max_epochs: 3000

K5:
  fixed:
    data_params:
      K: 5.0

    model_params:
      dropout: 0.0

    train_params:
      lr: 0.1
      weight_decay: 0.0100

    attack_params:
      surrogate_model_params:
        label: "LinearGCN"
        model: "LinearGCN"
        n_filter: 64
        dropout: 0.5
      surrogate_train_params:
        lr: 0.1
        weight_decay: 0.0100
        patience: 300
        max_epochs: 3000