seml:
  name: test
  executable: exp_train.py
  project_root_dir: ../../
  output_dir: log/

slurm:
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:1       # num GPUs
    mem: 10G          # memory
    cpus-per-task: 4  # num cores
    time: 0-00:30     # max time, D-HH:MM

fixed:

  model_params:
    label: GAT
    model: GAT
    n_heads: 8
    n_features_per_head: 8

  data_params:
    inductive_samples: 1000
  
  train_params:
    inductive: True

  other_params:
    sacred_metrics: False

grid:
  
  seed:
    type: range
    min: 0
    max: 2
    step: 1

K01:
  fixed:
    data_params:
      K: 0.1

    model_params:
      dropout: 0.0
      dropout_neighbourhood: 0.0

    train_params:
      lr: 0.10
      weight_decay: 0.0001
