seml:
  name: trn_lp
  executable: exp_train.py
  project_root_dir: ../../
  output_dir: log/training

slurm:
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:1       # num GPUs
    mem: 10G          # memory
    cpus-per-task: 4  # num cores
    time: 0-00:30     # max time, D-HH:MM

fixed:
  train_params:
    inductive: True

  model_params:
    label: LP
    model: None
    use_label_propagation: True
    lp_layers: 50

grid:
  data_params:
    K:
      type: choice
      options:
        - 0.1
        - 0.5
        - 1
        - 1.5
        - 2
        - 5

  model_params:
    lp_alpha:
      type: choice
      options:
        - 0.00
        - 0.05
        - 0.10
        - 0.15
        - 0.20
        - 0.25
        - 0.30
        - 0.35
        - 0.40
        - 0.45
        - 0.50
        - 0.55
        - 0.60
        - 0.65
        - 0.70
        - 0.75
        - 0.80
        - 0.85
        - 0.90
        - 0.95
        - 1.00
        
  seed:
    type: choice
    options:
      - 0
      - 1
      - 2
        
