seml:
  name: trn_gat
  executable: exp_train.py
  project_root_dir: ../../
  output_dir: log/training

slurm:
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:1       # num GPUs
    mem: 10G          # memory
    cpus-per-task: 4  # num cores
    time: 0-00:30     # max time, D-HH:MM

fixed:
  train_params:
    inductive: True

  model_params:
    label: APPNP
    model: APPNP
    n_hidden: 64
    K: 10
    alpha: 0.1

grid:
  data_params:
    K:
      type: choice
      options:
        - 0.1

  model_params:
    dropout:
      type: choice
      options:
        - 0.0

    dropout_neighbourhood:
      type: choice
      options:
        - 0.0

  train_params:
    lr: 
      type: choice
      options:
        - 0.1

    weight_decay:
      type: choice
      options:
        - 0.0001

  seed:
    type: choice
    options:
      - 1