seml:
  name: evaluate_arxiv
  executable: experiment_evaluate_overrobustness.py
  project_root_dir: ../..
  output_dir: config/evaluate/output

slurm:
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:1       # num GPUs
    mem: 16G
    cpus-per-task: 4  # num cores
    time: 0-10:00     # max time, D-HH:MM

fixed:
  artifact_dir: cache
  model_storage_type: overrobust
  device: 0
  data_device: 0
  make_undirected: True
  binary_attr: False
  data_dir: datasets/
  dataset: ogbn-arxiv
  metric: l2
  n_per_class: 20 # used to subsample test set

grid:
  seed:
    type: choice
    options:
      - 0
      - 1
      - 5
      - 6
      - 7
  model_label:
    type: choice
    options:
      - LP
      - GCN+LP
      - GCN
      #- APPNP
  projection:
    type: choice
    options:
      #- True
      - False
  lp_params:
    num_layers: 
      type: choice
      options:
        #- 1
        #- 5
        - 10
        #- 50
    alpha: 
      type: choice
      options:
        #- 0.2
        #- 0.3
        #- 0.4
        #- 0.5
        #- 0.6
        - 0.7
        #- 0.8