seml:
  name: eval_robustness_gcn
  executable: exp_eval_robustness.py
  project_root_dir: ../
  output_dir: log/

slurm:
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:1       # num GPUs
    mem: 10G          # memory
    cpus-per-task: 4  # num cores
    time: 0-00:30     # max time, D-HH:MM

fixed:
  model_params:
    label: GCN
    model: DenseGCN
    n_filters: 64

  data_params:
    inductive_samples: 1000
  
  train_params:
    inductive: True

grid:
  attack_params:
    attack: 
      type: choice
      options:
      - "l2"
  
  seed:
    type: choice
    options:
      - 9

K01:
  fixed:
    data_params:
      K: 0.1

    model_params:
      dropout: 0.5

    train_params:
      lr: 0.1
      weight_decay: 0.001
